import type { NextPage } from 'next';
import Head from 'next/head';
import ContactCards from '../components/ContactCards';
import Hero from '../components/Hero';
import Menu from '../components/Menu';
import SignUp from '../components/SignUp';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fudo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <ContactCards />
      <SignUp />
      <Menu />
    </div>
  )
}

export default Home
